import { NETWORK_SELECT_OPTIONS } from "@/lib/web3/chains";
import type { IntegrationPlugin } from "../registry";
import { registerIntegration } from "../registry";

const ARC_TOKENS = [
  { value: "USDC", label: "USDC" },
  { value: "EURC", label: "EURC" },
  { value: "cirBTC", label: "cirBTC" },
];

const fromNetwork = {
  key: "fromNetwork",
  label: "From network",
  type: "select" as const,
  options: NETWORK_SELECT_OPTIONS,
  defaultValue: "base",
  required: true,
};

const toNetwork = {
  key: "toNetwork",
  label: "To network",
  type: "select" as const,
  options: NETWORK_SELECT_OPTIONS,
  defaultValue: "arc-testnet",
  required: true,
};

const network = {
  key: "network",
  label: "Network",
  type: "select" as const,
  options: NETWORK_SELECT_OPTIONS,
  defaultValue: "arc-testnet",
};

const tokenSelect = {
  key: "token",
  label: "Token",
  type: "select" as const,
  options: [...ARC_TOKENS],
  defaultValue: "USDC",
};

const arcPlugin: IntegrationPlugin = {
  type: "arc",
  label: "Arc",
  description:
    "Arc Testnet App Kit flows: CCTP bridge, swap, send, unified balance, genesis tokens, deploy, StableFX.",
  formFields: [
    {
      id: "apiKey",
      label: "Circle API key",
      type: "password",
      placeholder: "Used for swap quotes and CCTP helpers",
      configKey: "apiKey",
      envVar: "CIRCLE_API_KEY",
      helpText: "Same Developer Services key as the Circle plugin. Get it from ",
      helpLink: { text: "console.circle.com", url: "https://console.circle.com" },
    },
    {
      id: "stablefxApiKey",
      label: "StableFX API key",
      type: "password",
      placeholder: "TEST key settles on Arc Testnet",
      configKey: "stablefxApiKey",
      envVar: "CIRCLE_STABLEFX_API_KEY",
      helpText: "Optional. Required only for StableFX quote, execute, and status.",
    },
  ],
  testConfig: {
    getTestFunction: async () => {
      const { testArc } = await import("./test");
      return testArc;
    },
  },
  actions: [
    {
      slug: "bridge-usdc",
      label: "Bridge USDC",
      description: "CCTP V2 burn with Arc Testnet as from or to",
      category: "Arc Bridge",
      stepFunction: "bridgeUsdcStep",
      stepImportPath: "bridge",
      outputFields: [{ field: "hash", description: "Burn hash" }],
      configFields: [
        fromNetwork,
        toNetwork,
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "recipient", label: "Recipient", type: "template-input" },
        {
          key: "transferSpeed",
          label: "Speed",
          type: "select",
          options: [
            { value: "fast", label: "Fast" },
            { value: "standard", label: "Standard" },
          ],
          defaultValue: "fast",
        },
        { key: "maxFee", label: "Max fee", type: "template-input" },
      ],
    },
    {
      slug: "retry-bridge",
      label: "Retry bridge",
      description: "Resume a failed burn/attestation/mint from stored output",
      category: "Arc Bridge",
      stepFunction: "retryBridgeStep",
      stepImportPath: "bridge",
      outputFields: [{ field: "hash", description: "Mint hash" }],
      configFields: [
        { key: "burnTxHash", label: "Burn tx hash", type: "template-input" },
        { key: "message", label: "Message hex", type: "template-textarea" },
        { key: "attestation", label: "Attestation hex", type: "template-textarea" },
        toNetwork,
      ],
    },
    {
      slug: "estimate-bridge",
      label: "Estimate bridge",
      description: "Estimate CCTP Fast vs standard fees",
      category: "Arc Bridge",
      stepFunction: "estimateBridgeStep",
      stepImportPath: "bridge",
      outputFields: [{ field: "minFinalityThreshold", description: "Finality" }],
      configFields: [
        fromNetwork,
        toNetwork,
        { key: "amount", label: "Amount", type: "template-input", required: true },
        {
          key: "transferSpeed",
          label: "Speed",
          type: "select",
          options: [
            { value: "fast", label: "Fast" },
            { value: "standard", label: "Standard" },
          ],
          defaultValue: "fast",
        },
      ],
    },
    {
      slug: "swap-on-arc",
      label: "Swap on Arc",
      description: "Quote a USDC / EURC / cirBTC swap on Arc Testnet",
      category: "Arc Swap",
      stepFunction: "swapOnArcStep",
      stepImportPath: "swap",
      outputFields: [{ field: "quote", description: "Quote" }],
      configFields: [
        { key: "fromToken", label: "From", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "toToken", label: "To", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
      ],
    },
    {
      slug: "swap-and-bridge",
      label: "Swap and bridge",
      description: "Same-chain swap then CCTP (or reverse)",
      category: "Arc Swap",
      stepFunction: "swapAndBridgeStep",
      stepImportPath: "swap",
      outputFields: [{ field: "quote", description: "Quote" }],
      configFields: [
        { key: "fromToken", label: "From", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "toToken", label: "To", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        {
          key: "destinationNetwork",
          label: "Bridge destination",
          type: "select",
          options: NETWORK_SELECT_OPTIONS,
        },
      ],
    },
    {
      slug: "get-swap-status",
      label: "Get swap status",
      description: "Poll a Circle swap quote or transaction",
      category: "Arc Swap",
      stepFunction: "getSwapStatusStep",
      stepImportPath: "swap",
      outputFields: [{ field: "data", description: "Status" }],
      configFields: [
        { key: "quoteId", label: "Quote ID", type: "template-input" },
        { key: "transactionHash", label: "Tx hash", type: "template-input" },
      ],
    },
    {
      slug: "estimate-swap",
      label: "Estimate swap",
      description: "Estimate an Arc swap",
      category: "Arc Swap",
      stepFunction: "estimateSwapStep",
      stepImportPath: "swap",
      outputFields: [{ field: "amount", description: "Amount" }],
      configFields: [
        { key: "fromToken", label: "From", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "toToken", label: "To", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
      ],
    },
    {
      slug: "send-on-arc",
      label: "Send on Arc",
      description: "Send native USDC or ERC-20 EURC/cirBTC. Gas is USDC.",
      category: "Arc Send",
      stepFunction: "sendOnArcStep",
      stepImportPath: "send",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        tokenSelect,
        { key: "to", label: "Recipient", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "estimate-send",
      label: "Estimate send",
      description: "Estimate an Arc send (20 Gwei USDC gas floor)",
      category: "Arc Send",
      stepFunction: "estimateSendStep",
      stepImportPath: "send",
      outputFields: [{ field: "maxFeePerGasWei", description: "Gas floor" }],
      configFields: [
        tokenSelect,
        { key: "to", label: "Recipient", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
      ],
    },
    {
      slug: "ub-deposit",
      label: "UB deposit",
      description: "Deposit USDC into Gateway from a source chain",
      category: "Arc Unified Balance",
      stepFunction: "ubDepositStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "hash", description: "Deposit hash" }],
      configFields: [
        network,
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "ub-deposit-for",
      label: "UB deposit for",
      description: "Credit another Gateway account",
      category: "Arc Unified Balance",
      stepFunction: "ubDepositForStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "hash", description: "Deposit hash" }],
      configFields: [
        network,
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "recipient", label: "Recipient", type: "template-input", required: true },
      ],
    },
    {
      slug: "ub-spend",
      label: "UB spend",
      description: "Gateway transfer targeting Arc. Requires a delegate-signed burn intent.",
      category: "Arc Unified Balance",
      stepFunction: "ubSpendStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "data", description: "Transfer" }],
      configFields: [
        { key: "delegate", label: "Delegate", type: "template-input", required: true },
        {
          key: "signedBurnIntent",
          label: "Signed burn intent JSON",
          type: "template-textarea",
          required: true,
        },
        network,
      ],
    },
    {
      slug: "ub-add-delegate",
      label: "UB add delegate",
      description: "Authorize a Gateway spend delegate",
      category: "Arc Unified Balance",
      stepFunction: "ubAddDelegateStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "delegate", label: "Delegate", type: "template-input", required: true },
      ],
    },
    {
      slug: "ub-remove-delegate",
      label: "UB remove delegate",
      description: "Revoke a Gateway spend delegate",
      category: "Arc Unified Balance",
      stepFunction: "ubRemoveDelegateStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "delegate", label: "Delegate", type: "template-input", required: true },
      ],
    },
    {
      slug: "ub-delegate-status",
      label: "UB delegate status",
      description: "Check whether a delegate is authorized",
      category: "Arc Unified Balance",
      stepFunction: "ubDelegateStatusStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "authorized", description: "Authorized" }],
      configFields: [
        network,
        { key: "depositor", label: "Depositor", type: "template-input", required: true },
        { key: "delegate", label: "Delegate", type: "template-input", required: true },
      ],
    },
    {
      slug: "ub-initiate-remove-fund",
      label: "UB initiate remove fund",
      description: "Start a Gateway withdrawal delay",
      category: "Arc Unified Balance",
      stepFunction: "ubInitiateRemoveFundStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "amount", label: "Amount", type: "template-input", required: true },
      ],
    },
    {
      slug: "ub-complete-remove-fund",
      label: "UB complete remove fund",
      description: "Complete a Gateway withdrawal after the delay",
      category: "Arc Unified Balance",
      stepFunction: "ubCompleteRemoveFundStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [network],
    },
    {
      slug: "ub-get-balances",
      label: "UB get balances",
      description: "Confirmed Gateway balances (optional pending)",
      category: "Arc Unified Balance",
      stepFunction: "ubGetBalancesStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "data", description: "Balances" }],
      configFields: [
        { key: "depositor", label: "Depositor", type: "template-input", required: true },
        network,
      ],
    },
    {
      slug: "estimate-spend",
      label: "Estimate spend",
      description: "Estimate a Gateway spend",
      category: "Arc Unified Balance",
      stepFunction: "estimateSpendStep",
      stepImportPath: "unified-balance",
      outputFields: [{ field: "note", description: "Estimate note" }],
      configFields: [
        { key: "amount", label: "Amount", type: "template-input" },
        { key: "destinationAddress", label: "Destination", type: "template-input" },
        { key: "destinationDomain", label: "Domain", type: "template-input", defaultValue: "26" },
      ],
    },
    {
      slug: "get-token-rates",
      label: "Get token rates",
      description: "Circle exchange quote for Arc tokens",
      category: "Arc Reads",
      stepFunction: "getTokenRatesStep",
      stepImportPath: "reads",
      outputFields: [{ field: "data", description: "Quote" }],
      configFields: [
        { key: "fromToken", label: "From", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "toToken", label: "To", type: "select", options: [...ARC_TOKENS], required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
      ],
    },
    {
      slug: "get-supported-chains",
      label: "Get supported chains",
      description: "Chains by operation: bridge, swap, send, unifiedBalance",
      category: "Arc Reads",
      stepFunction: "getSupportedChainsStep",
      stepImportPath: "reads",
      outputFields: [{ field: "chains", description: "Chains" }],
      configFields: [
        {
          key: "operation",
          label: "Operation",
          type: "select",
          options: [
            { value: "bridge", label: "Bridge" },
            { value: "swap", label: "Swap" },
            { value: "send", label: "Send" },
            { value: "unifiedBalance", label: "Unified balance" },
          ],
          defaultValue: "bridge",
        },
      ],
    },
    {
      slug: "get-arc-config",
      label: "Get Arc config",
      description: "RPC, explorer, chainId 5042002, CCTP domain 26",
      category: "Arc Reads",
      stepFunction: "getArcConfigStep",
      stepImportPath: "reads",
      outputFields: [{ field: "chainId", description: "Chain ID" }],
      configFields: [],
    },
    {
      slug: "list-genesis-addresses",
      label: "List genesis addresses",
      description: "USDC, EURC, USYC, CCTP, Gateway, StableFX, Memo, Permit2",
      category: "Arc Reads",
      stepFunction: "listGenesisAddressesStep",
      stepImportPath: "reads",
      outputFields: [{ field: "addresses", description: "Addresses" }],
      configFields: [],
    },
    {
      slug: "get-native-usdc-balance",
      label: "Get native USDC balance",
      description: "18-decimal gas USDC via eth_getBalance",
      category: "Arc Reads",
      stepFunction: "getNativeUsdcBalanceStep",
      stepImportPath: "reads",
      outputFields: [{ field: "balance", description: "Native USDC" }],
      configFields: [
        { key: "address", label: "Address", type: "template-input", required: true },
      ],
    },
    {
      slug: "get-usdc-erc20-balance",
      label: "Get USDC ERC-20 balance",
      description: "6-decimal ERC-20 USDC at 0x3600...0000",
      category: "Arc Reads",
      stepFunction: "getUsdcErc20BalanceStep",
      stepImportPath: "reads",
      outputFields: [{ field: "balance", description: "ERC-20 USDC" }],
      configFields: [
        { key: "address", label: "Address", type: "template-input", required: true },
      ],
    },
    {
      slug: "get-eurc-balance",
      label: "Get EURC balance",
      description: "EURC at 6 decimals",
      category: "Arc Reads",
      stepFunction: "getEurcBalanceStep",
      stepImportPath: "reads",
      outputFields: [{ field: "balance", description: "EURC" }],
      configFields: [
        { key: "address", label: "Address", type: "template-input", required: true },
      ],
    },
    {
      slug: "estimate-usdc-gas",
      label: "Estimate USDC gas",
      description: "20 Gwei maxFeePerGas floor",
      category: "Arc Reads",
      stepFunction: "estimateUsdcGasStep",
      stepImportPath: "reads",
      outputFields: [{ field: "minMaxFeePerGasWei", description: "Floor" }],
      configFields: [],
    },
    {
      slug: "wait-finality",
      label: "Wait finality",
      description: "Poll an Arc receipt until it is included",
      category: "Arc Reads",
      stepFunction: "waitFinalityStep",
      stepImportPath: "reads",
      outputFields: [{ field: "finalized", description: "Finalized" }],
      configFields: [
        { key: "txHash", label: "Transaction hash", type: "template-input", required: true },
      ],
    },
    {
      slug: "decode-system-emitter",
      label: "Decode system emitter",
      description: "Read USDC transfers from 0xffff...FfE",
      category: "Arc Reads",
      stepFunction: "decodeSystemEmitterStep",
      stepImportPath: "reads",
      outputFields: [{ field: "logs", description: "Logs" }],
      configFields: [
        { key: "fromBlock", label: "From block", type: "template-input" },
        { key: "toBlock", label: "To block", type: "template-input" },
      ],
    },
    {
      slug: "attach-memo",
      label: "Attach memo",
      description: "Call through the Arc Memo contract (preserves msg.sender)",
      category: "Arc Contracts",
      stepFunction: "attachMemoStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        { key: "target", label: "Target", type: "template-input", required: true },
        { key: "data", label: "Calldata", type: "template-textarea", required: true },
        { key: "memo", label: "Memo", type: "template-input" },
        { key: "value", label: "Value hex", type: "template-input" },
      ],
    },
    {
      slug: "deploy-on-arc",
      label: "Deploy on Arc",
      description: "Deploy bytecode via CREATE2 with USDC gas. Not SCP template deploy.",
      category: "Arc Contracts",
      stepFunction: "deployOnArcStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        { key: "bytecode", label: "Bytecode", type: "template-textarea", required: true },
        { key: "salt", label: "CREATE2 salt", type: "template-input" },
      ],
    },
    {
      slug: "read-contract",
      label: "Read contract",
      description: "eth_call on Arc Testnet",
      category: "Arc Contracts",
      stepFunction: "readContractStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "result", description: "Hex result" }],
      configFields: [
        { key: "contractAddress", label: "Contract", type: "template-input", required: true },
        { key: "data", label: "Calldata", type: "template-textarea", required: true },
      ],
    },
    {
      slug: "write-contract",
      label: "Write contract",
      description: "Privy-signed contract write on Arc",
      category: "Arc Contracts",
      stepFunction: "writeContractStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        { key: "contractAddress", label: "Contract", type: "template-input", required: true },
        { key: "data", label: "Calldata", type: "template-textarea", required: true },
        { key: "value", label: "Value hex", type: "template-input" },
      ],
    },
    {
      slug: "erc-8004-register",
      label: "ERC-8004 register",
      description: "Register an agent URI on an ERC-8004 registry",
      category: "Arc Contracts",
      stepFunction: "erc8004RegisterStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        { key: "registryAddress", label: "Registry", type: "template-input", required: true },
        { key: "agentUri", label: "Agent URI", type: "template-input", required: true },
      ],
    },
    {
      slug: "erc-8183-create-job",
      label: "ERC-8183 create job",
      description: "Create a job on an ERC-8183 registry",
      category: "Arc Contracts",
      stepFunction: "erc8183CreateJobStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        { key: "registryAddress", label: "Registry", type: "template-input", required: true },
        { key: "jobCalldata", label: "Job calldata", type: "template-textarea", required: true },
      ],
    },
    {
      slug: "usyc-info",
      label: "USYC info",
      description: "USYC, Teller, and Entitlements addresses plus eligibility note",
      category: "Arc Contracts",
      stepFunction: "usycInfoStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "usyc", description: "USYC address" }],
      configFields: [],
    },
    {
      slug: "stablefx-quote",
      label: "StableFX quote",
      description: "Request a taker FX quote. Uses CIRCLE_STABLEFX_API_KEY.",
      category: "Arc StableFX",
      stepFunction: "stablefxQuoteStep",
      stepImportPath: "stablefx",
      outputFields: [{ field: "data", description: "Quote" }],
      configFields: [
        { key: "fromCurrency", label: "From", type: "text", required: true, defaultValue: "USDC" },
        { key: "toCurrency", label: "To", type: "text", required: true, defaultValue: "EURC" },
        { key: "amount", label: "Amount", type: "template-input", required: true },
      ],
    },
    {
      slug: "stablefx-execute",
      label: "StableFX execute",
      description: "Accept a quote and create a taker trade",
      category: "Arc StableFX",
      stepFunction: "stablefxExecuteStep",
      stepImportPath: "stablefx",
      outputFields: [{ field: "data", description: "Trade" }],
      configFields: [
        { key: "quoteId", label: "Quote ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "stablefx-status",
      label: "StableFX status",
      description: "Get a StableFX trade by ID",
      category: "Arc StableFX",
      stepFunction: "stablefxStatusStep",
      stepImportPath: "stablefx",
      outputFields: [{ field: "data", description: "Trade" }],
      configFields: [
        { key: "tradeId", label: "Trade ID", type: "template-input", required: true },
      ],
    },
  ],
};

registerIntegration(arcPlugin);
export default arcPlugin;
