import { NETWORK_SELECT_OPTIONS } from "@/lib/web3/chains";
import type { IntegrationPlugin } from "../registry";
import { registerIntegration } from "../registry";

const CIRCLE_BLOCKCHAINS = [
  { value: "ETH", label: "Ethereum" },
  { value: "BASE", label: "Base" },
  { value: "ARB", label: "Arbitrum" },
  { value: "OP", label: "Optimism" },
  { value: "MATIC", label: "Polygon" },
  { value: "AVAX", label: "Avalanche" },
  { value: "ARC-TESTNET", label: "Arc Testnet" },
  { value: "ETH-SEPOLIA", label: "Ethereum Sepolia" },
  { value: "BASE-SEPOLIA", label: "Base Sepolia" },
  { value: "ARB-SEPOLIA", label: "Arbitrum Sepolia" },
];

const network = {
  key: "network",
  label: "Network",
  type: "select" as const,
  options: NETWORK_SELECT_OPTIONS,
  defaultValue: "arc-testnet",
  required: true,
};

const blockchain = {
  key: "blockchain",
  label: "Circle blockchain",
  type: "select" as const,
  options: [...CIRCLE_BLOCKCHAINS],
  defaultValue: "ARC-TESTNET",
};

const circlePlugin: IntegrationPlugin = {
  type: "circle",
  label: "Circle",
  description:
    "Developer wallets, CCTP V2, Gateway, nanopayments, Smart Contract Platform, USDC/EURC, and Circle Mint sandbox.",
  formFields: [
    {
      id: "apiKey",
      label: "Circle API key",
      type: "password",
      placeholder: "Developer Services key for api.circle.com",
      configKey: "apiKey",
      envVar: "CIRCLE_API_KEY",
      helpText: "Wallets, SCP, and swap quotes. Get a key from ",
      helpLink: {
        text: "console.circle.com",
        url: "https://console.circle.com",
      },
    },
    {
      id: "entitySecret",
      label: "Entity secret",
      type: "password",
      placeholder: "32-byte hex",
      configKey: "entitySecret",
      envVar: "CIRCLE_ENTITY_SECRET",
      helpText: "Required for developer-controlled wallet writes.",
    },
    {
      id: "mintApiKey",
      label: "Mint API key",
      type: "password",
      placeholder: "Sandbox key for api-sandbox.circle.com",
      configKey: "mintApiKey",
      envVar: "CIRCLE_MINT_API_KEY",
      helpText: "Circle Mint sandbox only. Do not mix with CIRCLE_API_KEY.",
    },
  ],
  testConfig: {
    getTestFunction: async () => {
      const { testCircle } = await import("./test");
      return testCircle;
    },
  },
  actions: [
    {
      slug: "create-wallet-set",
      label: "Create wallet set",
      description: "Create a developer-controlled wallet set",
      category: "Circle Wallets",
      stepFunction: "createWalletSetStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Wallet set" }],
      configFields: [{ key: "name", label: "Name", type: "template-input" }],
    },
    {
      slug: "create-wallet",
      label: "Create wallet",
      description: "Create a developer-controlled wallet",
      category: "Circle Wallets",
      stepFunction: "createWalletStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Wallets" }],
      configFields: [
        { key: "walletSetId", label: "Wallet set ID", type: "template-input", required: true },
        blockchain,
        {
          key: "accountType",
          label: "Account type",
          type: "select",
          options: [
            { value: "EOA", label: "EOA" },
            { value: "SCA", label: "SCA" },
          ],
          defaultValue: "EOA",
        },
        { key: "count", label: "Count", type: "template-input", defaultValue: "1" },
      ],
    },
    {
      slug: "get-wallet",
      label: "Get wallet",
      description: "Get a developer-controlled wallet",
      category: "Circle Wallets",
      stepFunction: "getWalletStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Wallet" }],
      configFields: [
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "list-wallets",
      label: "List wallets",
      description: "List developer-controlled wallets",
      category: "Circle Wallets",
      stepFunction: "listWalletsStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Wallets" }],
      configFields: [
        { key: "walletSetId", label: "Wallet set ID", type: "template-input" },
        blockchain,
        { key: "pageSize", label: "Page size", type: "template-input", defaultValue: "20" },
      ],
    },
    {
      slug: "list-balances",
      label: "List balances",
      description: "List balances for a Circle wallet",
      category: "Circle Wallets",
      stepFunction: "listBalancesStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Balances" }],
      configFields: [
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "create-transfer",
      label: "Create transfer",
      description: "Transfer from a developer-controlled wallet",
      category: "Circle Wallets",
      stepFunction: "createTransferStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Transaction" }],
      configFields: [
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
        { key: "destinationAddress", label: "Destination", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenId", label: "Token ID", type: "template-input" },
        { key: "tokenAddress", label: "Token address", type: "template-input" },
      ],
    },
    {
      slug: "get-transaction",
      label: "Get transaction",
      description: "Get a Circle wallet transaction",
      category: "Circle Wallets",
      stepFunction: "getTransactionStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Transaction" }],
      configFields: [
        { key: "transactionId", label: "Transaction ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "sign-typed-data",
      label: "Sign typed data",
      description: "Sign EIP-712 typed data with a Circle wallet",
      category: "Circle Wallets",
      stepFunction: "signTypedDataStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "data", description: "Signature" }],
      configFields: [
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
        { key: "typedData", label: "Typed data JSON", type: "template-textarea", required: true },
      ],
    },
    {
      slug: "deposit-for-burn",
      label: "Deposit for burn",
      description: "CCTP V2 burn on the source chain via the linked Privy wallet",
      category: "Circle CCTP",
      stepFunction: "depositForBurnStep",
      stepImportPath: "cctp",
      outputFields: [{ field: "hash", description: "Burn transaction hash" }],
      configFields: [
        network,
        {
          key: "destinationNetwork",
          label: "Destination",
          type: "select",
          options: NETWORK_SELECT_OPTIONS,
          required: true,
        },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "mintRecipient", label: "Mint recipient", type: "template-input", required: true },
        {
          key: "tokenSymbol",
          label: "Token",
          type: "select",
          options: [
            { value: "USDC", label: "USDC" },
            { value: "EURC", label: "EURC" },
          ],
          defaultValue: "USDC",
        },
        { key: "burnToken", label: "Burn token override", type: "template-input" },
        {
          type: "group",
          label: "Advanced",
          fields: [
            {
              key: "transferSpeed",
              label: "Speed",
              type: "select",
              options: [
                { value: "fast", label: "Fast (1000)" },
                { value: "standard", label: "Standard (2000)" },
              ],
              defaultValue: "fast",
            },
            { key: "maxFee", label: "Max fee", type: "template-input" },
            { key: "destinationCaller", label: "Destination caller", type: "template-input" },
          ],
        },
      ],
    },
    {
      slug: "get-iris-attestation",
      label: "Get Iris attestation",
      description: "Fetch a CCTP V2 attestation from Iris",
      category: "Circle CCTP",
      stepFunction: "getIrisAttestationStep",
      stepImportPath: "cctp",
      outputFields: [{ field: "data", description: "Attestation" }],
      configFields: [
        { key: "transactionHash", label: "Burn tx hash", type: "template-input", required: true },
        { key: "sourceDomain", label: "Source domain", type: "template-input", defaultValue: "26" },
        network,
      ],
    },
    {
      slug: "receive-mint",
      label: "Receive mint",
      description: "Submit a CCTP attestation on the destination chain",
      category: "Circle CCTP",
      stepFunction: "receiveMintStep",
      stepImportPath: "cctp",
      outputFields: [{ field: "hash", description: "Mint transaction hash" }],
      configFields: [
        network,
        { key: "message", label: "Message hex", type: "template-textarea", required: true },
        { key: "attestation", label: "Attestation hex", type: "template-textarea", required: true },
      ],
    },
    {
      slug: "get-domains",
      label: "Get domains",
      description: "List CCTP domains and USDC addresses",
      category: "Circle CCTP",
      stepFunction: "getDomainsStep",
      stepImportPath: "cctp",
      outputFields: [{ field: "domains", description: "Domain table" }],
      configFields: [],
    },
    {
      slug: "get-gateway-balances",
      label: "Get Gateway balances",
      description: "Read unified Gateway balances (no API key)",
      category: "Circle Gateway",
      stepFunction: "getGatewayBalancesStep",
      stepImportPath: "gateway",
      outputFields: [{ field: "data", description: "Balances" }],
      configFields: [
        { key: "address", label: "Depositor", type: "template-input" },
        { key: "token", label: "Token", type: "text", defaultValue: "USDC" },
        { key: "sourcesJson", label: "Sources JSON", type: "template-textarea" },
        network,
      ],
    },
    {
      slug: "create-gateway-transfer",
      label: "Create Gateway transfer",
      description: "Create a Gateway transfer attestation",
      category: "Circle Gateway",
      stepFunction: "createGatewayTransferStep",
      stepImportPath: "gateway",
      outputFields: [{ field: "data", description: "Attestation" }],
      configFields: [
        { key: "destinationAddress", label: "Recipient", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "destinationDomain", label: "Destination domain", type: "template-input", defaultValue: "26" },
        { key: "sourcesJson", label: "Sources JSON", type: "template-textarea" },
        network,
      ],
    },
    {
      slug: "deposit-to-gateway",
      label: "Deposit to Gateway",
      description: "Approve and deposit USDC into GatewayWallet",
      category: "Circle Nanopayments",
      stepFunction: "depositToGatewayStep",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "hash", description: "Deposit hash" }],
      configFields: [
        network,
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "get-nanopayment-balance",
      label: "Get nanopayment balance",
      description: "Read a Gateway / nanopayment balance",
      category: "Circle Nanopayments",
      stepFunction: "getNanopaymentBalanceStep",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "data", description: "Balance" }],
      configFields: [
        { key: "address", label: "Address", type: "template-input", required: true },
        network,
      ],
    },
    {
      slug: "check-x402-support",
      label: "Check x402 support",
      description: "GET a URL and parse 402 / PAYMENT-REQUIRED. Never Graph x402 URLs.",
      category: "Circle Nanopayments",
      stepFunction: "checkX402SupportStep",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "paymentRequired", description: "Whether HTTP 402" }],
      configFields: [{ key: "url", label: "URL", type: "template-input", required: true }],
    },
    {
      slug: "pay-x402",
      label: "Pay x402",
      description: "Sign EIP-3009 with Privy and retry. Refuses Graph x402 URLs.",
      category: "Circle Nanopayments",
      stepFunction: "payX402Step",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "signature", description: "EIP-3009 signature" }],
      configFields: [
        { key: "url", label: "URL", type: "template-input", required: true },
        network,
        { key: "payTo", label: "Pay to", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "settle-x402",
      label: "Settle x402",
      description: "Settle or search a Gateway nanopayment by nonce",
      category: "Circle Nanopayments",
      stepFunction: "settleX402Step",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "data", description: "Settlement" }],
      configFields: [
        { key: "authorizationJson", label: "Authorization JSON", type: "template-textarea" },
        { key: "nonce", label: "Nonce", type: "template-input" },
        network,
      ],
    },
    {
      slug: "discover-agent-services",
      label: "Discover agent services",
      description: "Public GET /v2/x402/discovery/resources (no key)",
      category: "Circle Nanopayments",
      stepFunction: "discoverAgentServicesStep",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "data", description: "Resources" }],
      configFields: [],
    },
    {
      slug: "withdraw-from-gateway",
      label: "Withdraw from Gateway",
      description: "Same-chain withdraw or cross-chain mint from Gateway",
      category: "Circle Nanopayments",
      stepFunction: "withdrawFromGatewayStep",
      stepImportPath: "nanopayments",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "amount", label: "Amount", type: "template-input", required: true },
        {
          key: "destinationNetwork",
          label: "Destination network",
          type: "select",
          options: NETWORK_SELECT_OPTIONS,
        },
        { key: "mintRecipient", label: "Mint recipient", type: "template-input" },
      ],
    },
    {
      slug: "import-contract",
      label: "Import contract",
      description: "Import a contract into Circle SCP",
      category: "Circle Contracts",
      stepFunction: "importContractStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Contract" }],
      configFields: [
        { key: "address", label: "Address", type: "template-input", required: true },
        blockchain,
        { key: "name", label: "Name", type: "template-input" },
        { key: "description", label: "Description", type: "template-textarea" },
      ],
    },
    {
      slug: "list-contracts",
      label: "List contracts",
      description: "List imported SCP contracts",
      category: "Circle Contracts",
      stepFunction: "listContractsStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Contracts" }],
      configFields: [blockchain],
    },
    {
      slug: "get-contract",
      label: "Get contract",
      description: "Get an SCP contract",
      category: "Circle Contracts",
      stepFunction: "getContractStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Contract" }],
      configFields: [
        { key: "contractId", label: "Contract ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "update-contract",
      label: "Update contract",
      description: "Update SCP contract metadata",
      category: "Circle Contracts",
      stepFunction: "updateContractStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Contract" }],
      configFields: [
        { key: "contractId", label: "Contract ID", type: "template-input", required: true },
        { key: "name", label: "Name", type: "template-input" },
        { key: "description", label: "Description", type: "template-textarea" },
      ],
    },
    {
      slug: "query-contract",
      label: "Query contract",
      description: "Read a contract through SCP",
      category: "Circle Contracts",
      stepFunction: "queryContractStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Result" }],
      configFields: [
        { key: "contractId", label: "Contract ID", type: "template-input" },
        { key: "address", label: "Address", type: "template-input" },
        blockchain,
        { key: "abiFunctionSignature", label: "ABI signature", type: "template-input" },
        { key: "abiParameters", label: "ABI parameters JSON", type: "template-textarea" },
      ],
    },
    {
      slug: "deploy-bytecode",
      label: "Deploy bytecode",
      description: "Deploy a contract from bytecode via SCP",
      category: "Circle Contracts",
      stepFunction: "deployBytecodeStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Deployment" }],
      configFields: [
        { key: "bytecode", label: "Bytecode", type: "template-textarea", required: true },
        blockchain,
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
        { key: "abiJson", label: "ABI JSON", type: "template-textarea" },
        { key: "constructorParameters", label: "Constructor JSON", type: "template-textarea" },
        { key: "name", label: "Name", type: "template-input" },
      ],
    },
    {
      slug: "deploy-template",
      label: "Deploy template",
      description: "Deploy an SCP template (ERC-20 / 721 / 1155 / Airdrop)",
      category: "Circle Contracts",
      stepFunction: "deployTemplateStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Deployment" }],
      configFields: [
        { key: "templateId", label: "Template ID", type: "template-input", required: true },
        blockchain,
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
        { key: "name", label: "Name", type: "template-input" },
        { key: "constructorParameters", label: "Template parameters JSON", type: "template-textarea" },
      ],
    },
    {
      slug: "estimate-deploy-fee",
      label: "Estimate deploy fee",
      description: "Estimate SCP deploy fee for bytecode or a template",
      category: "Circle Contracts",
      stepFunction: "estimateDeployFeeStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Fee estimate" }],
      configFields: [
        blockchain,
        { key: "walletId", label: "Wallet ID", type: "template-input", required: true },
        { key: "bytecode", label: "Bytecode", type: "template-textarea" },
        { key: "templateId", label: "Template ID", type: "template-input" },
      ],
    },
    {
      slug: "create-event-monitor",
      label: "Create event monitor",
      description: "Create an SCP event monitor",
      category: "Circle Contracts",
      stepFunction: "createEventMonitorStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Monitor" }],
      configFields: [
        { key: "contractId", label: "Contract ID", type: "template-input", required: true },
        { key: "eventName", label: "Event name", type: "template-input", required: true },
      ],
    },
    {
      slug: "list-event-monitors",
      label: "List event monitors",
      description: "List SCP event monitors",
      category: "Circle Contracts",
      stepFunction: "listEventMonitorsStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Monitors" }],
      configFields: [{ key: "contractId", label: "Contract ID", type: "template-input" }],
    },
    {
      slug: "update-event-monitor",
      label: "Update event monitor",
      description: "Enable or disable an event monitor",
      category: "Circle Contracts",
      stepFunction: "updateEventMonitorStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Monitor" }],
      configFields: [
        { key: "monitorId", label: "Monitor ID", type: "template-input", required: true },
        {
          key: "status",
          label: "Status",
          type: "select",
          options: [
            { value: "ENABLED", label: "Enabled" },
            { value: "DISABLED", label: "Disabled" },
          ],
          defaultValue: "ENABLED",
        },
      ],
    },
    {
      slug: "delete-event-monitor",
      label: "Delete event monitor",
      description: "Delete an SCP event monitor",
      category: "Circle Contracts",
      stepFunction: "deleteEventMonitorStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Result" }],
      configFields: [
        { key: "monitorId", label: "Monitor ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "list-event-logs",
      label: "List event logs",
      description: "List SCP event logs",
      category: "Circle Contracts",
      stepFunction: "listEventLogsStep",
      stepImportPath: "contracts",
      outputFields: [{ field: "data", description: "Logs" }],
      configFields: [
        { key: "contractId", label: "Contract ID", type: "template-input" },
        { key: "from", label: "From", type: "template-input" },
        { key: "to", label: "To", type: "template-input" },
      ],
    },
    {
      slug: "lookup-token-address",
      label: "Lookup token address",
      description: "Look up USDC or EURC by chain. Arc native USDC is 18-dec; ERC-20 is 6-dec.",
      category: "Circle Tokens",
      stepFunction: "lookupTokenAddressStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "address", description: "Token address" }],
      configFields: [
        network,
        {
          key: "symbol",
          label: "Token",
          type: "select",
          options: [
            { value: "USDC", label: "USDC" },
            { value: "EURC", label: "EURC" },
          ],
          defaultValue: "USDC",
          required: true,
        },
      ],
    },
    {
      slug: "get-usdc-balance",
      label: "Get USDC balance",
      description: "Read USDC. On Arc, returns native 18-dec and ERC-20 6-dec balances.",
      category: "Circle Tokens",
      stepFunction: "getUsdcBalanceStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "balance", description: "USDC balance" }],
      configFields: [
        network,
        { key: "address", label: "Address", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "get-eurc-balance",
      label: "Get EURC balance",
      description: "Read EURC (6 decimals)",
      category: "Circle Tokens",
      stepFunction: "getEurcBalanceStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "balance", description: "EURC balance" }],
      configFields: [
        network,
        { key: "address", label: "Address", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "transfer-usdc",
      label: "Transfer USDC",
      description: "Transfer USDC with the linked Privy wallet",
      category: "Circle Tokens",
      stepFunction: "transferUsdcStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "to", label: "Recipient", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "transfer-eurc",
      label: "Transfer EURC",
      description: "Transfer EURC with the linked Privy wallet",
      category: "Circle Tokens",
      stepFunction: "transferEurcStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "to", label: "Recipient", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "approve-usdc",
      label: "Approve USDC",
      description: "Approve a spender for USDC",
      category: "Circle Tokens",
      stepFunction: "approveUsdcStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        network,
        { key: "spender", label: "Spender", type: "template-input", required: true },
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "check-usdc-allowance",
      label: "Check USDC allowance",
      description: "Read a USDC allowance",
      category: "Circle Tokens",
      stepFunction: "checkUsdcAllowanceStep",
      stepImportPath: "tokens",
      outputFields: [{ field: "allowance", description: "Allowance" }],
      configFields: [
        network,
        { key: "owner", label: "Owner", type: "template-input", required: true },
        { key: "spender", label: "Spender", type: "template-input", required: true },
        { key: "tokenAddress", label: "Token override", type: "template-input" },
      ],
    },
    {
      slug: "ping",
      label: "Mint ping",
      description: "Ping Circle Mint sandbox configuration",
      category: "Circle Mint",
      stepFunction: "mintPingStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Configuration" }],
      configFields: [],
    },
    {
      slug: "get-balances",
      label: "Mint get balances",
      description: "Get Circle Mint sandbox balances",
      category: "Circle Mint",
      stepFunction: "mintGetBalancesStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Balances" }],
      configFields: [],
    },
    {
      slug: "mint-create-transfer",
      label: "Mint create transfer",
      description: "Create a Circle Mint onchain transfer",
      category: "Circle Mint",
      stepFunction: "mintCreateTransferStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Transfer" }],
      configFields: [
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "destinationAddress", label: "Destination", type: "template-input", required: true },
        { key: "chain", label: "Chain", type: "template-input", defaultValue: "ETH" },
        { key: "currency", label: "Currency", type: "text", defaultValue: "USD" },
      ],
    },
    {
      slug: "get-transfer",
      label: "Mint get transfer",
      description: "Get a Circle Mint transfer",
      category: "Circle Mint",
      stepFunction: "mintGetTransferStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Transfer" }],
      configFields: [
        { key: "transferId", label: "Transfer ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "list-transfers",
      label: "Mint list transfers",
      description: "List Circle Mint transfers",
      category: "Circle Mint",
      stepFunction: "mintListTransfersStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Transfers" }],
      configFields: [{ key: "pageSize", label: "Page size", type: "template-input" }],
    },
    {
      slug: "create-payment-intent",
      label: "Create payment intent",
      description: "Create a Circle Mint payment intent",
      category: "Circle Mint",
      stepFunction: "mintCreatePaymentIntentStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Payment intent" }],
      configFields: [
        { key: "amount", label: "Amount", type: "template-input", required: true },
        { key: "currency", label: "Currency", type: "text", defaultValue: "USD" },
      ],
    },
    {
      slug: "get-payment-intent",
      label: "Get payment intent",
      description: "Get a Circle Mint payment intent",
      category: "Circle Mint",
      stepFunction: "mintGetPaymentIntentStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Payment intent" }],
      configFields: [
        { key: "paymentIntentId", label: "Payment intent ID", type: "template-input", required: true },
      ],
    },
    {
      slug: "list-payments",
      label: "List payments",
      description: "List Circle Mint payments",
      category: "Circle Mint",
      stepFunction: "mintListPaymentsStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Payments" }],
      configFields: [{ key: "pageSize", label: "Page size", type: "template-input" }],
    },
    {
      slug: "create-payout",
      label: "Create payout",
      description: "Create a Mint payout. Wire/bank requires confirmDestructive = yes.",
      category: "Circle Mint",
      stepFunction: "mintCreatePayoutStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Payout" }],
      configFields: [
        { key: "amount", label: "Amount", type: "template-input", required: true },
        {
          key: "destinationType",
          label: "Destination type",
          type: "select",
          options: [
            { value: "blockchain", label: "Blockchain" },
            { value: "wire", label: "Wire" },
            { value: "bank", label: "Bank" },
          ],
          defaultValue: "blockchain",
        },
        { key: "destinationAddress", label: "Destination address", type: "template-input" },
        { key: "chain", label: "Chain", type: "template-input" },
        {
          key: "confirmDestructive",
          label: "Confirm wire/bank",
          type: "select",
          options: [
            { value: "no", label: "No" },
            { value: "yes", label: "Yes" },
          ],
          defaultValue: "no",
        },
      ],
    },
    {
      slug: "get-payout",
      label: "Get payout",
      description: "Get a Circle Mint payout",
      category: "Circle Mint",
      stepFunction: "mintGetPayoutStep",
      stepImportPath: "mint",
      outputFields: [{ field: "data", description: "Payout" }],
      configFields: [
        { key: "payoutId", label: "Payout ID", type: "template-input", required: true },
      ],
    },
  ],
};

registerIntegration(circlePlugin);
export default circlePlugin;
