/**
 * Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration:
 * 1. Create a new directory in plugins/ (e.g., plugins/my-integration/)
 * 2. Add your plugin files (index.tsx, steps/, codegen/, etc.)
 * 3. Run: pnpm discover-plugins (or it runs automatically on build)
 *
 * To remove an integration:
 * 1. Delete the plugin directory
 * 2. Run: pnpm discover-plugins (or it runs automatically on build)
 */

import "./protocol";
import "./ai-gateway";
import "./arc";
import "./blob";
import "./blockscout";
import "./circle";
import "./clerk";
import "./code";
import "./cowswap";
import "./discord";
import "./fal";
import "./fantasy-premier-league";
import "./firecrawl";
import "./github";
import "./hyperliquid";
import "./linear";
import "./math";
import "./perplexity";
import "./privy";
import "./resend";
import "./safe";
import "./sendgrid";
import "./slack";
import "./stripe";
import "./supabase";
import "./superagent";
import "./telegram";
import "./the-graph";
import "./treasury";
import "./v0";
import "./web3";
import "./webflow";
import "./webhook";

export type {
  ActionConfigField,
  ActionConfigFieldBase,
  ActionConfigFieldGroup,
  ActionWithFullId,
  IntegrationPlugin,
  PluginAction,
} from "./registry";

// Export the registry utilities
export {
  computeActionId,
  findActionById,
  flattenConfigFields,
  generateAIActionPrompts,
  getActionsByCategory,
  getAllActions,
  getAllDependencies,
  getAllEnvVars,
  getAllIntegrations,
  getCredentialMapping,
  getDependenciesForActions,
  getIntegration,
  getIntegrationLabels,
  getIntegrationTypes,
  getPluginEnvVars,
  getSortedIntegrationTypes,
  isFieldGroup,
  parseActionId,
  registerIntegration,
} from "./registry";
