import { NETWORK_SELECT_OPTIONS } from "@/lib/web3/chains";
import type { IntegrationPlugin } from "../registry";
import { registerIntegration } from "../registry";

const networkField = {
  key: "network",
  label: "Network",
  type: "select" as const,
  options: NETWORK_SELECT_OPTIONS,
  defaultValue: "ethereum",
  required: true,
};

const walletIdField = {
  key: "walletId",
  label: "Wallet ID",
  type: "template-input" as const,
  placeholder: "wallet_... or {{NodeName.id}}",
  example: "wallet_abc123",
  required: true,
};

const privyPlugin: IntegrationPlugin = {
  type: "privy",
  label: "Privy",
  description:
    "Manage Privy users and wallets. Sign messages and send gas-sponsored transactions.",
  formFields: [
    {
      id: "appId",
      label: "App ID",
      type: "text",
      placeholder: "Your Privy app ID",
      configKey: "appId",
      envVar: "PRIVY_APP_ID",
      helpText: "Get your App ID from ",
      helpLink: {
        text: "dashboard.privy.io",
        url: "https://dashboard.privy.io",
      },
    },
    {
      id: "appSecret",
      label: "App Secret",
      type: "password",
      placeholder: "Your Privy app secret",
      configKey: "appSecret",
      envVar: "PRIVY_APP_SECRET",
      helpText: "Get your App Secret from ",
      helpLink: {
        text: "dashboard.privy.io",
        url: "https://dashboard.privy.io",
      },
    },
  ],
  testConfig: {
    getTestFunction: async () => {
      const { testPrivy } = await import("./test");
      return testPrivy;
    },
  },
  actions: [
    {
      slug: "get-user",
      label: "Get user",
      description: "Fetch a Privy user by ID",
      category: "Privy",
      stepFunction: "getUserStep",
      stepImportPath: "users",
      outputFields: [
        { field: "id", description: "Privy user ID" },
        { field: "linked_accounts", description: "Linked accounts" },
        { field: "wallets", description: "User wallets" },
      ],
      configFields: [
        {
          key: "privyUserId",
          label: "Privy user ID",
          type: "template-input",
          placeholder: "did:privy:... or {{NodeName.id}}",
          example: "did:privy:abc123",
          required: true,
        },
      ],
    },
    {
      slug: "list-wallets",
      label: "List wallets",
      description: "List wallets in the Privy app",
      category: "Privy",
      stepFunction: "listWalletsStep",
      stepImportPath: "wallets",
      outputFields: [{ field: "wallets", description: "Wallets" }],
      configFields: [],
    },
    {
      slug: "create-wallet",
      label: "Create wallet",
      description: "Create a new Privy server wallet",
      category: "Privy",
      stepFunction: "createWalletStep",
      stepImportPath: "wallets",
      outputFields: [
        { field: "id", description: "Wallet ID" },
        { field: "address", description: "Wallet address" },
        { field: "chain_type", description: "Chain type" },
      ],
      configFields: [
        {
          key: "chainType",
          label: "Chain type",
          type: "select",
          options: [
            { value: "ethereum", label: "Ethereum" },
            { value: "solana", label: "Solana" },
          ],
          defaultValue: "ethereum",
          required: true,
        },
      ],
    },
    {
      slug: "get-wallet",
      label: "Get wallet",
      description: "Fetch a Privy wallet by ID",
      category: "Privy",
      stepFunction: "getWalletStep",
      stepImportPath: "wallets",
      outputFields: [
        { field: "id", description: "Wallet ID" },
        { field: "address", description: "Wallet address" },
        { field: "chain_type", description: "Chain type" },
      ],
      configFields: [walletIdField],
    },
    {
      slug: "send-sponsored-transaction",
      label: "Send sponsored transaction",
      description: "Send a gas-sponsored transaction from a Privy wallet",
      category: "Privy",
      stepFunction: "sendSponsoredTransactionStep",
      stepImportPath: "sign-send",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        walletIdField,
        networkField,
        {
          key: "to",
          label: "To",
          type: "template-input",
          placeholder: "0x...",
          example: "0x0000000000000000000000000000000000000000",
          required: true,
        },
        {
          key: "data",
          label: "Calldata",
          type: "template-textarea",
          placeholder: "0x",
          example: "0x",
        },
        {
          key: "value",
          label: "Value",
          type: "template-input",
          placeholder: "0x0 or 0.01",
          example: "0x0",
        },
      ],
    },
    {
      slug: "sign-message",
      label: "Sign message",
      description: "Sign a message with a Privy wallet",
      category: "Privy",
      stepFunction: "signMessageStep",
      stepImportPath: "sign-send",
      outputFields: [{ field: "signature", description: "Hex signature" }],
      configFields: [
        walletIdField,
        networkField,
        {
          key: "message",
          label: "Message",
          type: "template-textarea",
          placeholder: "Message to sign",
          example: "Hello from Privy",
          required: true,
        },
      ],
    },
    {
      slug: "sign-typed-data",
      label: "Sign typed data",
      description: "Sign EIP-712 typed data with a Privy wallet",
      category: "Privy",
      stepFunction: "signTypedDataStep",
      stepImportPath: "sign-send",
      outputFields: [{ field: "signature", description: "Hex signature" }],
      configFields: [
        walletIdField,
        networkField,
        {
          key: "typedData",
          label: "Typed data JSON",
          type: "template-textarea",
          placeholder: '{"domain":{},"types":{},"primaryType":"","message":{}}',
          required: true,
        },
      ],
    },
    {
      slug: "transfer",
      label: "Transfer",
      description: "Transfer native tokens with Privy gas sponsorship",
      category: "Privy",
      stepFunction: "transferStep",
      stepImportPath: "sign-send",
      outputFields: [{ field: "hash", description: "Transaction hash" }],
      configFields: [
        walletIdField,
        networkField,
        {
          key: "to",
          label: "Recipient",
          type: "template-input",
          placeholder: "0x...",
          required: true,
        },
        {
          key: "amount",
          label: "Amount",
          type: "template-input",
          placeholder: "0.01",
          required: true,
        },
      ],
    },
    {
      slug: "get-transaction",
      label: "Get transaction",
      description: "Fetch a Privy wallet transaction by ID",
      category: "Privy",
      stepFunction: "getTransactionStep",
      stepImportPath: "wallets",
      outputFields: [
        { field: "transaction", description: "Transaction object" },
      ],
      configFields: [
        walletIdField,
        {
          key: "transactionId",
          label: "Transaction ID",
          type: "template-input",
          placeholder: "tx_... or {{NodeName.hash}}",
          required: true,
        },
      ],
    },
    {
      slug: "wallet-transfer",
      label: "Wallet transfer (USDC)",
      description:
        "Transfer USDC via Privy wallet actions API with optional bridging or conversion",
      category: "Privy",
      stepFunction: "walletTransferStep",
      stepImportPath: "wallet-actions",
      outputFields: [
        { field: "id", description: "Wallet action ID" },
        { field: "intent_id", description: "Intent ID when routed through intents" },
        { field: "status", description: "Action or intent status" },
        { field: "transaction_hash", description: "Onchain transaction hash" },
        { field: "mode", description: "direct or intent" },
      ],
      configFields: [
        walletIdField,
        {
          key: "sourceChain",
          label: "Source chain",
          type: "select",
          options: [
            { value: "base_sepolia", label: "Base Sepolia" },
            { value: "base", label: "Base" },
            { value: "ethereum_sepolia", label: "Ethereum Sepolia" },
          ],
          defaultValue: "base_sepolia",
          required: true,
        },
        {
          key: "sourceAsset",
          label: "Source asset",
          type: "select",
          options: [{ value: "usdc", label: "USDC" }],
          defaultValue: "usdc",
          required: true,
        },
        {
          key: "amount",
          label: "Amount",
          type: "template-input",
          placeholder: "10.00",
          required: true,
        },
        {
          key: "destinationAddress",
          label: "Destination address",
          type: "template-input",
          placeholder: "0x... or {{Payee.address}}",
          required: true,
        },
        {
          key: "destinationChain",
          label: "Destination chain",
          type: "select",
          options: [
            { value: "base_sepolia", label: "Base Sepolia" },
            { value: "base", label: "Base" },
            { value: "ethereum_sepolia", label: "Ethereum Sepolia" },
          ],
        },
        {
          key: "destinationAsset",
          label: "Destination asset",
          type: "select",
          options: [{ value: "usdc", label: "USDC" }],
        },
        {
          key: "useIntent",
          label: "Route as intent",
          type: "select",
          options: [
            { value: "false", label: "No (auto if policy allows)" },
            { value: "true", label: "Yes (quorum approval)" },
          ],
          defaultValue: "false",
        },
      ],
    },
    {
      slug: "wallet-swap",
      label: "Wallet swap",
      description: "Swap assets via Privy wallet actions API",
      category: "Privy",
      stepFunction: "walletSwapStep",
      stepImportPath: "wallet-actions",
      outputFields: [
        { field: "id", description: "Wallet action ID" },
        { field: "status", description: "Action status" },
        { field: "transaction_hash", description: "Transaction hash" },
      ],
      configFields: [
        walletIdField,
        {
          key: "chain",
          label: "Chain",
          type: "select",
          options: [
            { value: "base_sepolia", label: "Base Sepolia" },
            { value: "base", label: "Base" },
          ],
          defaultValue: "base_sepolia",
          required: true,
        },
        {
          key: "fromAsset",
          label: "From asset",
          type: "template-input",
          placeholder: "usdc",
          required: true,
        },
        {
          key: "toAsset",
          label: "To asset",
          type: "template-input",
          placeholder: "usdc",
          required: true,
        },
        {
          key: "amount",
          label: "Amount",
          type: "template-input",
          placeholder: "10.00",
          required: true,
        },
      ],
    },
    {
      slug: "create-policy",
      label: "Create policy",
      description: "Create a Privy authorization policy",
      category: "Privy",
      stepFunction: "createPolicyStep",
      stepImportPath: "wallet-actions",
      outputFields: [
        { field: "id", description: "Policy ID" },
        { field: "name", description: "Policy name" },
      ],
      configFields: [
        {
          key: "name",
          label: "Policy name",
          type: "text",
          required: true,
        },
        {
          key: "chainType",
          label: "Chain type",
          type: "select",
          options: [{ value: "ethereum", label: "Ethereum" }],
          defaultValue: "ethereum",
        },
        {
          key: "rulesJson",
          label: "Rules JSON",
          type: "template-textarea",
          placeholder: '[{"name":"Allow transfer","method":"transfer","action":"ALLOW","conditions":[]}]',
          required: true,
        },
        {
          key: "ownerId",
          label: "Owner quorum ID",
          type: "template-input",
          placeholder: "key_quorum_...",
        },
      ],
    },
    {
      slug: "create-key-quorum",
      label: "Create key quorum",
      description: "Create a Privy key quorum for org approvals",
      category: "Privy",
      stepFunction: "createKeyQuorumStep",
      stepImportPath: "wallet-actions",
      outputFields: [
        { field: "id", description: "Key quorum ID" },
        { field: "display_name", description: "Display name" },
      ],
      configFields: [
        {
          key: "displayName",
          label: "Display name",
          type: "text",
          required: true,
        },
        {
          key: "authorizationThreshold",
          label: "Authorization threshold",
          type: "text",
          placeholder: "1",
          required: true,
        },
        {
          key: "userIdsJson",
          label: "User IDs JSON",
          type: "template-textarea",
          placeholder: '["did:privy:..."]',
        },
      ],
    },
    {
      slug: "create-transfer-intent",
      label: "Create transfer intent",
      description: "Propose a transfer intent for owner quorum approval",
      category: "Privy",
      stepFunction: "createTransferIntentStep",
      stepImportPath: "wallet-actions",
      outputFields: [
        { field: "intent_id", description: "Intent ID" },
        { field: "status", description: "Intent status" },
      ],
      configFields: [
        walletIdField,
        {
          key: "sourceChain",
          label: "Source chain",
          type: "select",
          options: [
            { value: "base_sepolia", label: "Base Sepolia" },
            { value: "base", label: "Base" },
          ],
          defaultValue: "base_sepolia",
          required: true,
        },
        {
          key: "sourceAsset",
          label: "Source asset",
          type: "select",
          options: [{ value: "usdc", label: "USDC" }],
          defaultValue: "usdc",
          required: true,
        },
        {
          key: "amount",
          label: "Amount",
          type: "template-input",
          required: true,
        },
        {
          key: "destinationAddress",
          label: "Destination address",
          type: "template-input",
          required: true,
        },
      ],
    },
    {
      slug: "get-intent",
      label: "Get intent",
      description: "Fetch Privy intent status",
      category: "Privy",
      stepFunction: "getIntentStep",
      stepImportPath: "wallet-actions",
      outputFields: [
        { field: "intent_id", description: "Intent ID" },
        { field: "status", description: "Intent status" },
      ],
      configFields: [
        {
          key: "intentId",
          label: "Intent ID",
          type: "template-input",
          placeholder: "intent_... or {{NodeName.intent_id}}",
          required: true,
        },
      ],
    },
  ],
};

registerIntegration(privyPlugin);
export default privyPlugin;
