syntax = "proto3";

package kelp.backing.v1;

message BackingSnapshot {
  string id = 1;
  uint64 block_number = 2;
  int32 deviation_bps = 3;
  bool should_alert = 4;
  string mainnet_supply = 5;
  string arb_supply = 6;
  string total_supply = 7;
  string total_backing_eth = 8;
  string excess_eth = 9;
  string mainnet_supply_eth = 10;
  string arb_supply_eth = 11;
  string total_supply_eth = 12;
  string total_backing_eth_human = 13;
  string excess_eth_human = 14;
  string deviation_pct = 15;
  int32 threshold_bps = 16;
}

message BackingSnapshots {
  repeated BackingSnapshot snapshots = 1;
}

message ArbRsethSupply {
  string supply = 1;
  uint64 block_number = 2;
}
